# Generated by Django 4.2 on 2023-05-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_remove_account_follows_account_follows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
