# Generated by Django 4.2 on 2023-05-04 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answer', '0002_rename_downvote_answer_downvote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
