# Generated by Django 4.2 on 2023-05-04 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_answer_downvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
