# Generated by Django 4.2 on 2023-05-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_alter_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-upvote_count']},
        ),
    ]
