# Generated by Django 4.2 on 2023-05-26 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answer', '0007_alter_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hasDownvoted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='hasUpvoted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='downvote',
            field=models.ManyToManyField(null=True, related_name='downvote_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(null=True, related_name='upvote_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
