# Generated by Django 4.2 on 2023-05-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomment',
            old_name='downvote',
            new_name='downvote_count',
        ),
        migrations.RenameField(
            model_name='answercomment',
            old_name='upvote',
            new_name='upvote_count',
        ),
    ]
