# Generated by Django 4.2 on 2023-05-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_rename_downvote_answer_downvote_count_and_more'),
        ('comment', '0002_rename_downvote_answercomment_downvote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to='answer.answer'),
        ),
    ]
