# Generated by Django 4.2 on 2023-05-09 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
        ('comment', '0006_answercomment_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='downvote',
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionComments', to='question.question'),
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='upvote',
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDetail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote_question_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote_question_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
