# Generated by Django 4.2 on 2023-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_questioncomment_downvote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='hasDownvoted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='hasUpvoted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='hasDownvoted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='hasUpvoted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
